services:
  mongodb:
    image: mongo:7
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB:-watchparty_dev}
      # TODO: Add MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD when re-enabling authentication
    volumes:
      - ./mongo-data:/data/db
